# you can configure multiple hubs
[[Hubs]]
    # the name of the hub
    name = "HUB-1"
    # either use the existing db file or not
    keep_data = false

    # disable messengers by commenting out the corresponding block
    [Hubs.Discord]
        bot_token = ""
        channel_id = ""

    [Hubs.Slack]
        # your bot token, the one that starts with "xoxb-"
        bot_token = ""
        # your app token, the one that starts with "xoxa-"
        app_token = ""
        channel_id = ""

    [Hubs.CQHttp]
        ws_url = ""
        http_url = ""
        group_id = ""


[Pygeon]
    cache_path = "cache"
