# you can configure multiple hubs
[Clients]
    [Discord]
        bot_token = ""

    [Slack]
# your bot token, the one that starts with "xoxb-"
        bot_token = ""
# your app token, the one that starts with "xoxa-"
        app_token = ""

    [CQHttp]
        ws_url = ""
        http_url = ""



[[Hubs]]
    # the name of the hub
    name = "HUB-1"
    # either use the existing db file or not
    keep_data = false

    # disable messengers by commenting out the corresponding block
    [Hubs.Discord]
        channel_id = ""

    [Hubs.Slack]    
        channel_id = ""

    [Hubs.CQHttp]
        group_id = ""


[Bygeon]
    cache_path = "cache"
